# Site settings
title: Oretachi
email: info@oretachi.co
url: https://oretachi.co
description: "Oretachi, derived from the Japanese word that lit. means we are; to us symbolizes who we are. Click to find out more"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Oretachi

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: instagram
    url: https://www.instagram.com/oretachi.co/
  - title: facebook
    url: 
  - title: google plus
    url:
  - title: pinterest
    url:
  - title: github source
    url: https://github.com/Shirotobi/shirotobi.github.io

# Build settings
markdown: kramdown
permalink: pretty
